### ISSUE TITLE
Error when start code.

### ISSUE THREAD

**Issue by takisp08** [Arkanic/rtljs#3]
Hello, I try to run code with rtljs but wehn run code send this error message:
Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (C:\Users\geopa\Desktop\sdr\node_modules\ffi-napi\lib\dynamic_library.js:75:11)
    at Object.Library (C:\Users\geopa\Desktop\sdr\node_modules\ffi-napi\lib\library.js:47:10)
    at Object.<anonymous> (C:\Users\geopa\Desktop\sdr\node_modules\rtljs\lib\baremetal.js:26:40)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\geopa\Desktop\sdr\node_modules\rtljs\lib\rtlsdr-static.js:27:30)

I have v16.17.0 version node.js.

**Comment by Arkanic** [comment]
thats because I haven't added windows support just yet
give me a minute or two

**Comment by Arkanic** [comment]
closing this, as it isn't actually an issue on my end
what you need to do is install "librtlsdr" on your windows machine

in particular you need to make sure that the librtlsdr.dll is in a system path so that it is accessible to the code.

Good luck!
